Repository EmakinaFR/docker-magento2, pull requests merged in 2019-02, with the labels that each got.

#31 Add m2-hotfixes folder in delegated volumes list
  Makefile
  docker-compose.yml
Labels: enhancement

#32 Exclude elements in rsync only in root
  Makefile
Labels: bug, enhancement

#33 Multiple fixes related to dependencies management
  .circleci/config.yml
  Makefile
  docker-compose.yml
  php/Dockerfile
Labels: bug

#34 Add a command to export internal environment variables
  Makefile
Labels: enhancement

#35 Replace manual rsync by docker-rsync
  .circleci/config.yml
  Makefile
  docker-compose.yml
  docker-sync.yml
  nginx/Dockerfile
  php/Dockerfile
Labels: enhancement
